### ISSUE TITLE
no lesson 4 or 5

### ISSUE THREAD

**Issue by bazinski** [AAROC/AnsibleBootCamp#20]
Lesson4.? and Lesson5.? are missing or are they to be inferred from the more colourfully named slides in the directory?

Deeper into Ansible.pdf and is the same as lesson3.pdf.
Introduction to Ansible.pdf appears to be the same as lesson2.pdf
I assume Setting the stage.pdf is lesson1.

**Comment by brucellino** [comment]
Thanks @bazinski I'll take a look and fix it. The model was that the files have  names like "setting the stage" and so on, but if someone besides  me is giving the bootcamp they won't know what order to give the talks in, so we need to link the files to numbered ones. I think I made a mistake with the links.

**Comment by bazinski** [comment]
I have no problem with setting the stage etc. 
Everything seems to finish at lesson 3 but then there is lesson6.pdf?
Maybe just remove lesso6 then and put something in the readme, or a title pdf linking to the others?
